# Site
repository: https://github.com/jaszhou1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jason Zhou
title: PhD Candidate
email: jason.sm.zhou@gmail.com
website: https://github.com/jaszhou1

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: https://twitter.com/ArgonautZhou
github_username:  jaszhou1
linkedin_username: jason-zhou-875691158
orcid_username: 0000-0003-4229-6009

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 I'm a PhD candidate in the field of mathematical psychology. My speciality is using a combination of experimentation (both on the web and in the laboratory) and computational models to understand how people make decisions about the content of their memory over time.
 
 I'm excited, in general, by the application of modelling to develop novel insights into why things happen (i.e. the specific processes that govern some phenomenon). I also enjoy communicating these sorts of insights by visualising my analyses and finding the story in complex data.

content:
  - title: Technical Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Languages: I am most skilled in <mark>R</mark> (base and tidyverse) and <mark>MATLAB</mark>, but have also worked with Python, HTML, Javascript, and SQL
      - Other: Git, Microsoft Office, Google App Engine, online survey design and recruitment (e.g. Prolific, Amazon Mechanical Turk)
      - Statistics: Mixed-effects modelling, factor analysis, multiple regression
      
  - title: Publications # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - A circular diffusion model of continuous-outcome source memory retrieval Contrasting continuous and threshold accounts (HTML)[https://link.springer.com/article/10.3758/s13423-020-01862-0]
      - The Spatiotemporal Gradient of Intrusion Errors in Continuous Outcome Source Memory: Source Retrieval is Affected by both Guessing and Intrusions (PDF)[https://psyarxiv.com/kpwh4/]
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The University of Melbourne
        caption: 2018 - Present
        sub_title: PhD, Psychology
        description: | # this will include new lines to allow paragraphs
          During my candidature, I learnt most of my key skills that I hope to apply and grow throughout my career. I also developed soft skills that I think will prove useful in meeting new challenges, such as working to deadline and managing expectations and morale. 

          I spent time in my earlier years as a committee member of *Graduate Researchers in Psychological Sciences* (GRiPS) taking on roles such as *Secretary* and *President*, where I worked with my peers to foster a warm and collaborative network.
      - layout: left
        title:
        caption: 2014 - 2017
        subtitle: Bachelor of Arts (Honours)
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Melbourne School of Psychological Sciences
        sub_title: Teaching Assistant
        caption: 2022
        description: | # this will include new lines to allow paragraphs
            Assisted with subject co-ordination with a large cohort of ~2000 students.
      - layout: left
        title: 
        sub_title: Tutor
        caption: 2018 - 2019
        description: | # this will include new lines to allow paragraphs
            Taught introductory first-year level psychology subject (Mind Brain & Behaviour) over three semesters. Participated in workshops on improving student mental health and wellbeing within MSPS.
  
  - title: Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Postgraduate Student Research Excellence Award, *Melbourne School of Psychological Sciences* 2021
      - Jeff Pressing Prize, *Melbourne School of Psychological Sciences* 2017
      - Dean's Honours List, *Faculty of Arts, The University of Melbourne* 2014, 2017

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
